# Generated by Django 2.1.4 on 2018-12-27 10:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCoordinatorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('image', models.ImageField(upload_to='images/events/coordinators/')),
                ('phn_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
                ('branch', models.CharField(max_length=30)),
                ('year', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('details', models.TextField(null=True)),
                ('rules', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('venue', models.CharField(max_length=130)),
                ('faculty_name', models.CharField(max_length=130)),
                ('faculty_image', models.ImageField(upload_to='images/events/faculty/')),
                ('department', models.CharField(max_length=130)),
                ('maxp', models.IntegerField(default=6)),
                ('image', models.ImageField(upload_to='images/events/')),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('university_roll', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th')], default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('aadhar_no', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 16', regex='^.{16}$')])),
                ('phn_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('regs_id', models.CharField(max_length=130, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=130)),
                ('college_code', models.CharField(max_length=10)),
                ('faculty_name', models.CharField(max_length=50)),
                ('faculty_designation', models.CharField(max_length=130)),
                ('faculty_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('faculty_phn_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
                ('faculty_email', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.EventModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('has_email_verified', models.BooleanField(default=False)),
                ('verification_key', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.AddField(
            model_name='eventparticipantmodel',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.EventRegistrationModel'),
        ),
        migrations.AddField(
            model_name='eventcoordinatormodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='main.EventModel'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistrationmodel',
            unique_together={('college_code', 'event')},
        ),
    ]
