# Generated by Django 2.1.4 on 2019-01-15 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190114_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFacultyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=130, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/events/faculty/')),
                ('designation', models.CharField(blank=True, max_length=130, null=True)),
                ('department', models.CharField(blank=True, max_length=30, null=True)),
                ('phn_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
            ],
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='faculty_image',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='faculty_name',
        ),
        migrations.AddField(
            model_name='eventfacultymodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='main.EventModel'),
        ),
    ]
