# Generated by Django 2.1.4 on 2018-12-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.CharField(default='timezone.now', max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact',
            field=models.BigIntegerField(default=92929292),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default=23309333, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=339039489, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rollno',
            field=models.BigIntegerField(default=300494895),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
