# Generated by Django 2.1.4 on 2019-01-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190115_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfacultymodel',
            name='view_priority',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
