# Generated by Django 2.1.4 on 2018-12-08 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_eventmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='usereventmodel',
            name='events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EventModel'),
        ),
        migrations.AddField(
            model_name='usereventmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
