# Generated by Django 2.1.4 on 2018-12-09 01:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20181209_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usereventmodel',
            old_name='events',
            new_name='event',
        ),
        migrations.AlterUniqueTogether(
            name='usereventmodel',
            unique_together={('user', 'event')},
        ),
    ]
