# Generated by Django 2.1.4 on 2018-12-22 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181209_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCoordinatorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('img_url', models.CharField(max_length=200, null=True)),
                ('phn_no', models.BigIntegerField(null=True)),
                ('branch', models.CharField(max_length=30)),
                ('year', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('fathers_name', models.CharField(max_length=130)),
                ('university_roll', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=30)),
                ('year', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=20)),
                ('aadhar_no', models.CharField(max_length=20)),
                ('phn_no', models.BigIntegerField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('regs_id', models.CharField(max_length=130, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=130)),
                ('college_code', models.CharField(max_length=10)),
                ('faculty_name', models.CharField(max_length=130)),
                ('faculty_designation', models.CharField(max_length=130)),
                ('faculty_phn_no', models.BigIntegerField()),
                ('faculty_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AlterUniqueTogether(
            name='usereventmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usereventmodel',
            name='event',
        ),
        migrations.RemoveField(
            model_name='usereventmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rollno',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='department',
            field=models.CharField(default=222, max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='faculty_name',
            field=models.CharField(default='ffdd', max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='maxp',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='venue',
            field=models.CharField(default='ddd', max_length=130),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserEventModel',
        ),
        migrations.AddField(
            model_name='eventregistrationmodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.EventModel'),
        ),
        migrations.AddField(
            model_name='eventparticipantmodel',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.EventRegistrationModel'),
        ),
        migrations.AddField(
            model_name='eventcoordinatormodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='main.EventModel'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistrationmodel',
            unique_together={('college_code', 'event')},
        ),
    ]
