# Generated by Django 2.1.4 on 2018-12-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181222_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='image',
            field=models.ImageField(default='sss', upload_to=''),
            preserve_default=False,
        ),
    ]
