# Generated by Django 2.1.4 on 2018-12-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_eventmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='image',
            field=models.ImageField(upload_to='images/events/'),
        ),
    ]
