# Generated by Django 2.1.4 on 2018-12-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181225_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='faculty_image',
            field=models.ImageField(default='ddd', upload_to='images/events/faculty/'),
            preserve_default=False,
        ),
    ]
